### ISSUE TITLE
Identify a job scheduling service

### ISSUE THREAD

**Issue by smjorge22** [miroculus/puppeteer#1]
### Basic features expected of job scheduler software include:
1. interfaces which help to define workflows and/or job dependencies
2. automatic submission of executions
3. interfaces to monitor the executions
4. priorities and/or queues to control the execution order of unrelated jobs

e.g. 
1. https://pypi.python.org/pypi/luigi 
2. http://help.mortardata.com/technologies/luigi/building_your_pipeline
3. http://supervisord.org/
4. http://www.celeryproject.org/
5. http://www.open-mpi.org/  libs

**Comment by agar3s** [comment]
http://stackoverflow.com/questions/21967398/python-based-asynchronous-workflow-modules-what-is-difference-between-celery-w

**Comment by agar3s** [comment]
https://labs.spotify.com/2013/03/20/how-we-use-python-at-spotify/
